<a href="https://colab.research.google.com/github/eliseev-mk/lab10_emk/blob/main/lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
vector_1 = np.array([1, 2, 3, 4])
vector_2 = np.array([5, 6, 7, 8])
vector_3 = np.array([9, 10, 11])
matrix = np.column_stack((vector_1, vector_2, vector_3))

### Почему нейросети

Нейросети справляются с задачами компьютерного зрения лучше, чем модели других типов — пора разобраться, почему.

##### Объекты и признаки

Линейная регрессия, случайный лес и градиентный бустинг работают хорошо на табличных данных: в строках записываются объекты, а в столбцах — их признаки. А есть датасеты из фотографий, по которым нужно определить пол или возраст человека. Что тогда будет объектом и признаком?

Предположим, что объект — это фотография, а каждый пиксель — признак этого объекта.

Пример

Вы уже знаете, что алгоритм «видит» пиксель как набор чисел, характеризующих его цвет. В случае с цветными RGB-изображениями каждый пиксель описан набором из трёх чисел, которые обозначают интенсивность красного, зелёного и синего цветов. В большинстве случаев мы сталкиваемся именно с такими картинками.

Однако для простоты вы начнёте осваивать компьютерное зрение с одноцветных, чёрно-белых изображений. Цвет каждого их пикселя — оттенок серого, заданный одним числом.

На первой картинке чёрно-белое изображение низкого разрешения. На второй — это же изображение с указанием оттенков серого цвета от 0 (чёрный) до 255 (белый). Именно в таком диапазоне лежит значение яркости пикселя чёрно-белого изображения, то есть возможное значение признака. А на третьей — сами эти цифры.


Чтобы получить признаки, нужно представить значения пикселей в виде вектора:


In [ ]:
[255, 255, 255, 255, 237, 217, 239, 255, 255, 255, 255, 255, 255, 255, 255, 190, 75, 29, 29, 30, 81, 198, 255, 255, 255, 255, 255, 147, 30, 29, 29, 29, 29, 29, 31, 160, 255, 255, 255, 185, 29, 29, 29, 29, 29, 29, 29, 29, 31, 198, 255, 255, 61, 29, 29, 29, 29, 29, 29, 29, 29, 29, 74, 255, 255, 108, 121, 121, 121, 121, 121, 121, 121, 121, 121, 102, 219, 255, 250, 255, 255, 255, 255, 255, 255, 255, 255, 255, 238, 107, 168, 255, 238, 153, 150, 152, 244, 201, 152, 150, 178, 253, 103, 144, 248, 243, 121, 108, 114, 225, 184, 130, 112, 154, 235, 103, 62, 197, 255, 227, 168, 231, 149, 230, 196, 179, 251, 183, 29, 29, 105, 255, 255, 219, 195, 191, 184, 195, 235, 255, 91, 29, 29, 30, 187, 255, 234, 218, 218, 218, 218, 243, 174, 29, 29, 29, 29, 38, 180, 255, 255, 255, 255, 255, 169, 35, 29, 29, 29, 29, 29, 29, 82, 153, 174, 150, 76, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29]

#####Чем ещё полезны нейросети
Рассмотрите другой пример. Датасет — текстовые описания товаров в интернет-магазине. Нужно определить категорию, к которой принадлежит каждый товар.

Вы помните, что преобразовать текст в численный формат поможет техника мешка слов. Сначала для каждого слова создаётся новый столбец. Если слово есть в описании товара, в столбце ставится 1, если нет — 0. Если в описании 10–20 слов, логистическую регрессию на преобразованном датасете можно обучить. Когда слов сотни, этот способ кодирования уже не работает. Но избавившись от порядка следования слов, можно потерять и смысл текста. Если же применить n-граммы, признаков станет ещё больше: классические методы снова не справятся.
<img src ='https://github.com/trisha00001/file/blob/main/Screenshot_2020-04-06_at_12.22.32_1586164961.png?raw=true'>
Что объединяет изображения и тексты?

1. Информация в них избыточна. Например, пиксели фона фотографии не так значимы при определении возраста, как морщины или седина. А предлоги и союзы не столь важны для определения смысла текста, как существительные и глаголы. Справиться с большим числом признаков помогут нейронные сети.
2. Соседние признаки связаны друг с другом. Зачастую соседние пиксели на изображении принадлежат одному объекту, а рядом стоящие слова в предложении связаны по смыслу. Если перемешать столбцы в табличных данных, их смысл не поменяется; если пиксели в изображении — будет шум, с которым уже ничего сделать нельзя. Учитывать порядок признаков умеют нейронные сети.

### Библиотека Keras

Keras (греч. κέρας, «рог») — это простая и компактная библиотека, созданная инженером компании Google Франсуа Шолле. По сути это интерфейс для работы с другой, более сложной библиотекой — TensorFlow (англ. «поток тензоров»). Это открытая библиотека, разработка команды исследовательского проекта Google Brain.

Сперва вы узнаете, как написать линейную регрессию в Keras. Линейная регрессия — это тоже нейронная сеть, но лишь с одним нейроном!
В начале темы вы будете работать с данными из прошлых курсов:

In [ ]:
import pandas as pd

data = pd.read_csv('/datasets/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

В sklearn код выглядел бы так:


In [ ]:
# подключение sklearn
from sklearn.linear_model import LinearRegression

# создание модель
model = LinearRegression()

# обучить модель
model.fit(features, target)

В Keras этот же код такой:

In [ ]:
# подключение Keras
from tensorflow import keras

# создание модели
model = keras.models.Sequential()
# параметры нейронной сети
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))
# как обучается нейронная сеть
model.compile(loss='mean_squared_error', optimizer='sgd')

# обучить модель
model.fit(features, target)

Что означает этот код? Первая строка подключает Keras из библиотеки TensorFlow. В тренажёре используется TensorFlow версии 2.1.0.

In [ ]:
from tensorflow import keras

Следующая строка инициализирует нейронную сеть. Модели задаётся класс Sequential (англ. «последовательный»). Этот класс применяется для моделей, в которых слои идут последовательно. Слой (англ. layer) — набор нейронов с общим входом и выходом.

In [ ]:
model = keras.models.Sequential()

Сеть будет состоять лишь из одного нейрона, или значения на одном выходе. В ней n входов, каждый умножается на свой вес. Например, x₁ умножается на w₁. Есть ещё один вход, который всегда равен единице. Его вес обозначается b (англ. bias, «смещение»). Именно из подбора весов w и b состоит процесс обучения нейронной сети. После того как все произведения значений входов на веса просуммированы, на выход подаётся ответ нейронной сети (а).
<img src= 'https://github.com/trisha00001/file/blob/main/x1_1586165939.jpg?raw=true'>

Команда keras.layers.Dense() (англ. «густые слои в Keras») создаёт один слой нейронов. «Густой» означает, что каждый вход будет соединён с каждым нейроном, или выходом. Параметр units (англ. «части») задаёт количество нейронов в слое, а input_dim (от англ. dimension, «размерность») — количество входов в слое. Причём в этом параметре смещение не учитывается.

Слой для сети создаётся так:

In [ ]:
# количество входов берётся из обучающей выборки
keras.layers.Dense(units=1, input_dim=features.shape[1])

Слои, в которых все входы соединены со всеми нейронами, называются полносвязными слоями (англ. fully connected layers). Вот как выглядит полносвязный слой, задаваемый командой keras.layers.Dense(units=2, input_dim=3):

<img src= 'https://github.com/trisha00001/file/blob/main/x1_1586166308.jpg?raw=true'>

Чтобы к модели добавить созданный слой, вызовите метод model.add() (англ. «добавить в модель»):

In [ ]:
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))

Обратите внимание на эту строчку:

In [ ]:
 model.compile(loss='mean_squared_error', optimizer='sgd')

Она готовит модель к обучению. После этой команды конструкцию сети уже нельзя будет изменить. В параметре loss указана функция потерь для задачи регрессии — MSE. В параметре optimizer='sgd' (англ. «оптимизатор») задан метод градиентного спуска. Запомните: нейронные сети обучаются SGD.

Теперь можно запустить обучение модели:

In [ ]:
model.fit(features, target)

Задание

1. Обучите модель линейной регрессии средствами библиотеки Keras. Метод fit() напечатает на экране прогресс обучения и значение ошибки. Чтобы формат ответа был понятным, добавьте в этот метод аргумент verbose=2, где 2 означает вывод в консоль. Если указать 0, то его не будет вовсе; если — 1, то вывод предназначен для Jupyter Notebook.

In [ ]:
import pandas as pd
from tensorflow import keras

data = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

# создание модели
model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))

# компиляция модели
model.compile(loss='mean_squared_error', optimizer='sgd')

# обучение модели
model.fit(features, target, verbose=2)

32/32 - 1s - loss: 9.5013 - 613ms/epoch - 19ms/step


2. Подберите такое количество эпох, чтобы получить MSE стабильно меньше 6.55. Добавить эпохи можно, указав аргумент epochs в методе model.fit().

In [ ]:
import pandas as pd
from tensorflow import keras

data = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(features, target, epochs=5, verbose=2)

Epoch 1/5
32/32 - 0s - loss: 9.1070 - 307ms/epoch - 10ms/step
Epoch 2/5
32/32 - 0s - loss: 7.1987 - 42ms/epoch - 1ms/step
Epoch 3/5
32/32 - 0s - loss: 6.6685 - 50ms/epoch - 2ms/step
Epoch 4/5
32/32 - 0s - loss: 6.5111 - 42ms/epoch - 1ms/step
Epoch 5/5
32/32 - 0s - loss: 6.5007 - 39ms/epoch - 1ms/step


3.
Найдите значение функции потерь на валидационной выборке. Передайте модели  валидационную выборку в аргументе validation_data метода model.fit(). Загрузка валидационной выборки уже в прекоде.

In [ ]:
import pandas as pd
from tensorflow import keras

data_train = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/train_data_n.csv')
features_train = data_train.drop('target', axis=1)
target_train = data_train['target']

data_valid = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/test_data_n.csv')
features_valid = data_valid.drop('target', axis=1)
target_valid = data_valid['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1]))
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(features_train, target_train, epochs=5, validation_data=(features_valid, target_valid), verbose=2)

Epoch 1/5
32/32 - 1s - loss: 9.5064 - val_loss: 7.3481 - 961ms/epoch - 30ms/step
Epoch 2/5
32/32 - 0s - loss: 7.2613 - val_loss: 6.8922 - 159ms/epoch - 5ms/step
Epoch 3/5
32/32 - 0s - loss: 6.7154 - val_loss: 6.7988 - 193ms/epoch - 6ms/step
Epoch 4/5
32/32 - 0s - loss: 6.5678 - val_loss: 6.7244 - 250ms/epoch - 8ms/step
Epoch 5/5
32/32 - 0s - loss: 6.4872 - val_loss: 6.8009 - 249ms/epoch - 8ms/step



###Логистическая регрессия

Линейная регрессия — это нейронная сеть с одним нейроном. Логистическая — тоже. Чем же они различаются?

Если классов у объектов всего два, то разница между линейной и логистической регрессиями почти незаметна. Нужно добавить всего один элемент.

Вот как выглядит линейная регрессия:
<img src='https://github.com/trisha00001/file/blob/main/x1_1586166632.jpg?raw=true'>

А вот так — логистическая:

<img src = 'https://github.com/trisha00001/file/blob/main/x1-1_1586166651.jpg?raw=true'>

В схему добавилась сигмоидная функция (англ. sigmoid function), или знакомая вам функция активации нейрона. На вход она принимает любое действительное число, а возвращает число в диапазоне от 0 (активации нет) до 1 (активация есть).

$\sigma(z)=\frac{1}{1+e^{x}}$

где e — число Эйлера; приблизительно равно 2.718281828.

Это число в диапазоне от 0 до 1 можно трактовать как предсказание нейронной сети, к какому классу относится объект — отрицательному или положительному.

<img src = 'https://github.com/trisha00001/file/blob/main/1222.png?raw=true'>

Если сумма произведений значений входов на веса (z) очень большая, то на выходе сигмоиды получится число, близкое к единице:

<img src ='https://github.com/trisha00001/file/blob/main/jpg_1586166722.jpg?raw=true'>

Если сумма, наоборот, — большое отрицательное число, то функция вернёт число, близкое к нулю:

<img src = 'https://github.com/trisha00001/file/blob/main/21111.png?raw=true'>

Функция потерь меняется в зависимости от типа нейронной сети. Если в задаче регрессии применяли MSE, то для бинарной классификации подходит Binary Cross-Entropy, BCE (англ. «бинарная кросс-энтропия»). Метрику accuracy применять не получится: у неё нет производной, поэтому SGD работать не будет.

ВСЕ вычисляется так:

Все = - log(p)

где p — вероятность правильного ответа. Основание логарифма не играет роли, потому что изменение основания — это умножение функции потерь на константу и оно не меняет минимум.

Если значение целевого признака — 1, то вероятность правильного ответа равна:

$p=\sigma(x)$

Если значение целевого признака — 0, то p равна:

$p=(1 - \sigma(x)$)

Чтобы лучше разобраться с функцией ВСЕ, рассмотрите её график.

<img src = 'https://github.com/trisha00001/file/blob/main/log_1586166842.jpg?raw=true'>

Если вероятность правильного ответа p приблизительно равна единице, то -log(p) — положительное число, близкое к нулю. То есть ошибка маленькая.

Когда вероятность правильного ответа p≈0, то -log(p) — большое положительное число. Ошибка тоже большая.

### Логистическая регрессия в Keras
Вы написали линейную регрессию в Keras. Пора приступить к логистической.
Чтобы получить логистическую регрессию, код линейной нужно поменять лишь в двух местах:



1. К полносвязному слою примените функцию активации:

In [ ]:
keras.layers.Dense(units=1, input_dim=features_train.shape[1],
                   activation='sigmoid')

2. Поменяйте функцию потерь MSE на binary_crossentropy.

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='sgd')

Задание
1. Обучите логистическую регрессию на данных, загруженных в прекоде. Установите количество эпох, равным пяти.
Чтобы напечатать прогресс обучения, задайте аргумент verbose=2 в функции fit().

In [ ]:
import pandas as pd
from tensorflow import keras

df = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd')
model.fit(features_train, target_train, epochs=5, validation_data=(features_valid, target_valid), verbose=2)


Epoch 1/5
32/32 - 1s - loss: 0.8880 - val_loss: 0.8884 - 703ms/epoch - 22ms/step
Epoch 2/5
32/32 - 0s - loss: 0.8566 - val_loss: 0.8664 - 100ms/epoch - 3ms/step
Epoch 3/5
32/32 - 0s - loss: 0.8282 - val_loss: 0.8472 - 132ms/epoch - 4ms/step
Epoch 4/5
32/32 - 0s - loss: 0.8031 - val_loss: 0.8293 - 112ms/epoch - 3ms/step
Epoch 5/5
32/32 - 0s - loss: 0.7808 - val_loss: 0.8140 - 101ms/epoch - 3ms/step


2.
Найдите accuracy модели на валидационной выборке. Предсказания модели вычисляются функцией predict(), как в sklearn. Сигмоида вернёт числа от 0 до 1, преобразуйте их в классы, сравнив с 0.5.

Напечатайте на экране значение accuracy (уже в прекоде). Чтобы выводу не мешал прогресс обучения, задайте verbose=0.

In [ ]:
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score

df = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd')
model.fit(features_train, target_train, epochs=5, verbose=0, validation_data=(features_valid, target_valid))

predictions = model.predict(features_valid) > 0.5
score = accuracy_score(target_valid, predictions)
print("Accuracy:", score)

32/32 [==============================] - 0s 2ms/step
Accuracy: 0.495


3.
Обучение нейронной сети обычно занимает много времени. Сделайте так, чтобы отследить качество модели можно было на каждой эпохе. Для этого добавьте параметр metrics=['acc'] (от англ. accuracy) в методе compile().

Чтобы улучшить значение accuracy, обучите модель на десяти эпохах.

In [ ]:
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('https://raw.githubusercontent.com/trisha00001/file/main/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']


model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1],
                             activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['acc'])
model.fit(features_train, target_train, epochs=10, verbose=2,
          validation_data=(features_valid, target_valid))

Epoch 1/10
32/32 - 2s - loss: 0.8554 - acc: 0.5280 - val_loss: 0.8828 - val_acc: 0.4900 - 2s/epoch - 53ms/step
Epoch 2/10
32/32 - 0s - loss: 0.8237 - acc: 0.5410 - val_loss: 0.8594 - val_acc: 0.4900 - 187ms/epoch - 6ms/step
Epoch 3/10
32/32 - 0s - loss: 0.7956 - acc: 0.5430 - val_loss: 0.8389 - val_acc: 0.4930 - 164ms/epoch - 5ms/step
Epoch 4/10
32/32 - 0s - loss: 0.7711 - acc: 0.5480 - val_loss: 0.8211 - val_acc: 0.4980 - 167ms/epoch - 5ms/step
Epoch 5/10
32/32 - 0s - loss: 0.7500 - acc: 0.5500 - val_loss: 0.8056 - val_acc: 0.4970 - 169ms/epoch - 5ms/step
Epoch 6/10
32/32 - 0s - loss: 0.7315 - acc: 0.5630 - val_loss: 0.7905 - val_acc: 0.5000 - 161ms/epoch - 5ms/step
Epoch 7/10
32/32 - 0s - loss: 0.7142 - acc: 0.5730 - val_loss: 0.7778 - val_acc: 0.5120 - 148ms/epoch - 5ms/step
Epoch 8/10
32/32 - 0s - loss: 0.7000 - acc: 0.5850 - val_loss: 0.7683 - val_acc: 0.5200 - 243ms/epoch - 8ms/step
Epoch 9/10
32/32 - 0s - loss: 0.6877 - acc: 0.5960 - val_loss: 0.7593 - val_acc: 0.5260 - 182ms/ep

### Полносвязные нейронные сети

В этом уроке вы познакомитесь с полносвязными нейронными сетями (англ. fully connected neural networks), где в каждом слое любой нейрон связан с каждым нейроном предыдущего слоя.

Вот пример такой сети. Скрытыми слоями (англ. hidden layers) называются все слои, кроме входного и выходного.


<img src = 'https://github.com/trisha00001/file/blob/main/nejron3_1586167349.jpg?raw=true'>

В полносвязных сетях после каждого нейрона, кроме последнего, есть функция активации. Интересно, почему? Посмотрите на пример такой сети без веса b:


<img src = 'https://github.com/trisha00001/file/blob/main/x1_1586167365.jpg?raw=true'>

Чтобы получить z, нужно просуммировать произведения значений входов на веса:


In [ ]:
z1 = x1 * w11 + x2 * w12
z2 = x1 * w21 + x2 * w22
z3 = z1 * w31 + z2 * w32

Получается:

In [ ]:
z3 = (x1 * w11 + x2 * w12) * w31 + (w21 * x1 + w22 * x2) * w32

Вынесите за скобки x₁ и x₂:

In [ ]:
z3 = x1 * (w11 * w31 + w21 * w32) + x2 * (w12 * w31 + w22 * w32)

Для удобства стоит ввести новые обозначения w₁ и w₂:

In [ ]:
w1' = w11 * w31 + w21 * w32
w2' = w12 * w31 + w22 * w32

Итого:

In [ ]:
z3 = x1 * w1' + x2 * w2'

Вот как можно проиллюстрировать эту формулу:

<img src = 'https://github.com/trisha00001/file/blob/main/sadaefx1_1586167416.jpg?raw=true'>

Ничего не напоминает? Многослойная сеть — это сеть с одним нейроном!
Чтобы это исправить, верните сигмоиду и посмотрите, как поменяется сеть:


<img src ='https://github.com/trisha00001/file/blob/main/safadx1_1586167442.jpg?raw=true'>

Вот как записать это формулой:

In [ ]:
z1 = σ(x1 * w11 + x2 * w12)
z2 = σ(x1 * w21 + x2 * w22)
z3 = z1 * w31 + z2 * w32

Результат:

In [ ]:
z3 =  σ(x1 * w11 + x2 * w12) * w31 + σ(w21 * x1 + w22 * x2) * w32

Из-за сигмоид вынести за скобки x₁ и x₂ нельзя, а значит это уже не просто один нейрон. Сигмоида позволяет сделать сеть сложнее.

###Как учатся нейронные сети

Вы разобрали, как строятся многослойные сети. Как же они обучаются? Как и линейная регрессия — градиентным спуском. Параметры — это веса у нейронов в каждом полносвязном слое. А обучение заключается в поиске таких параметров, при которых функция потерь минимальна.

Интересно, как меняется нейронная сеть с добавлением нейронов и слоёв? Чтобы это узнать, решите несколько задач на сайте [TensorFlow Playground](https://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.03&regularizationRate=0&noise=0&networkShape=4,2&seed=0.02868&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false). Площадка позволяет обучить небольшие нейронные сети на модельных данных с двумя признаками для задачи классификации.

В левой части интерфейса TensorFlow Playground можно выбрать набор данных. В центре  изображено устройство сети. Справа выводится результат обучения. В верхней панели можно управлять обучением модели: менять значение эпохи, скорость обучения или функцию активации.

Посмотрите [на такую сеть](https://playground.tensorflow.org/#activation=sigmoid&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.1&regularizationRate=0&noise=0&networkShape=4,4,4,4&seed=0.29689&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false). В ней много слоёв и сигмоидная функция активации. Попробуйте обучить сеть. Она не обучится ни при какой величине шага.
В чём дело? С увеличением количества слоёв обучение ухудшается. Чем больше слоёв в сети, тем меньше сигнала от входа доходит до выхода сети. Это называется затуханием сигнала (англ. vanishing signal). Причина затухания кроется в сигмоиде, преобразующей большие значения в маленькие по много раз.
Чтобы избавиться от затухания сигнала, можно выбрать другую функцию активации. Например, ReLU (англ. Rectified Linear Unit, «выпрямленное линейное преобразование»):


<img src = 'https://github.com/trisha00001/file/blob/main/jpg_1586168291.jpg?raw=true'>

Вот формула ReLU:

ReLU(x) = max (0, x)

ReLU приводит к нулю всё, что меньше 0, и пропускает положительные значения без изменений.

У [этой сети ](https://playground.tensorflow.org/#activation=sigmoid&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.1&regularizationRate=0&noise=0&networkShape=4,4,4,4&seed=0.29689&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false)поменяйте функцию активации с сигмоиды на ReLU. Убедитесь, что нейронная сеть теперь обучается корректно. Из-за смены функции активации разделяющая точки разных цветов поверхность выглядит как многоугольник. Вид фигуры зависит от исходной инициализации весов сети.

Можете потренироваться ещё на последней обучающей выборке. Добейтесь успешного обучения сети, для этого подберите функцию активации, количество скрытых слоев и нейронов в них, а также шаг градиентного спуска.

###Полносвязные нейронные сети в Keras

Полносвязные слои в Keras создаются вызовом метода Dense(). Что нужно сделать, чтобы построить многослойную полносвязную сеть? Несколько раз добавить полносвязный слой! Чем больше слоёв, тем сложнее модель.

###Работа с изображениями в Python

Вы уже умеете открывать картинки в Python с помощью библиотеки OpenCV. В этом уроке вы научитесь работать с этими изображениями, переводя их в NumPy-массив.  

Вы уже знаете, что изображения — это набор чисел. Если изображение чёрно-белое, то в каждом пикселе хранится число от 0 (чёрный) до 255 (белый).

<img src = 'https://github.com/trisha00001/file/blob/main/log_1586169165.jpg?raw=true'>

Для загрузки картинки используем уже знакомую вам библиотеку OpenCV. Затем будем работать с ним, как c NumPy-массивом:

In [ ]:
import numpy as np
from PIL import Image

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)
print(array)

[[255 255 255 255 237 217 239 255 255 255 255 255 255]

 [255 255 190  75  29  29  30  81 198 255 255 255 255]

 [255 147  30  29  29  29  29  29  31 160 255 255 255]

 [185  29  29  29  29  29  29  29  29  31 198 255 255]

 [ 61  29  29  29  29  29  29  29  29  29  74 255 255]

 [108 121 121 121 121 121 121 121 121 121 102 219 255]

 [250 255 255 255 255 255 255 255 255 255 238 107 168]

 [255 238 153 150 152 244 201 152 150 178 253 103 144]

 [248 243 121 108 114 225 184 130 112 154 235 103  62]

 [197 255 227 168 231 149 230 196 179 251 183  29  29]

 [105 255 255 219 195 191 184 195 235 255  91  29  29]

 [ 30 187 255 234 218 218 218 218 243 174  29  29  29]

 [ 29  38 180 255 255 255 255 255 169  35  29  29  29]

 [ 29  29  29  82 153 174 150  76  29  29  29  29  29]

 [ 29  29  29  29  29  29  29  29  29  29  29  29  29]]

Задача

1.
Постройте изображение вызовом функции plt.imshow() (от англ. image show, «показать изображение»). Дополнительные аргументы указывать не нужно.

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# Приведение масштаба к [0, 1]
array = array / 255.

plt.imshow(array, cmap='gray')
plt.colorbar()


2.
Изучите функцию imshow() и добавьте аргумент, который сделает цветовую гамму чёрно-белой. Затем добавьте к изображению шкалу цвета вызовом функции colorbar() (англ. «цветовая шкала»):

In [ ]:
plt.colorbar()

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

plt.imshow(array, cmap='gray')
plt.colorbar()
plt.show()


3.
Перекрасьте верхний левый угол изображения в чёрный цвет (значение 0), а нижний правый — в белый (255). С изображением можно работать как с двумерным массивом.

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# Перекрасить верхний левый угол в чёрный
array[0, 0] = 0

# Перекрасить нижний правый угол в белый
array[14, 12] = 255

plt.imshow(array, cmap='gray')
plt.colorbar()

4.
Чтобы нейронные сети обучались лучше, обычно на вход им передают изображения в диапазоне от 0 до 1.

Приведите масштаб [0, 255] к [0, 1]. Для этого поделите все значения двумерного массива на 255.

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# Приведение масштаба к [0, 1]
array = array / 255.

plt.imshow(array, cmap='gray')
plt.colorbar()

### Цветные изображения

С чёрно-белым изображениями всё понятно, а как работать с цветными? Вы уже знаете, что цветные RGB-изображения состоят из трёх каналов: красного, зелёного и синего. По сути такие изображения — это трёхмерные массивы, в ячейках которых могут быть целые числа от 0 до 255.


<img src = 'https://raw.githubusercontent.com/trisha00001/file/main/jpg_1586169482.jpg'>

Трёхмерные массивы в NumPy устроены так же, как и двумерные.
Сравните, как они создаются:

In [ ]:
np.array([[0, 255], [255, 0]])

In [ ]:
np.array([[[0, 255, 0], [128, 0, 255]],
                    [[12, 89, 0], [5,  89, 245]]])

В трёхмерном массиве, полученном из изображения, всё так же: первая координата — это номер строки, вторая — номер столбца. Ещё добавляется третья координата — номер канала.

То есть трёхмерный массив — это всё тот же двумерный массив, аналогичный чёрно-белому изображению. Только в каждом пикселе этого массива хранятся три числа: яркость красного, зелёного и синего каналов.

Перейдём к задачам. Фото гангста-кота взяли с сайта: www.petful.com,

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

plt.imshow(array)

Задание

1.
Убедитесь, что каналы хранятся в третьей координате. Для этого выведите размер массива, полученного из картинки.

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

print(array.shape)

plt.imshow(array)
plt.show()

2.
Изобразите на экране канал только с красным цветом.

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

red_channel = array[:, :, 0]  # Получение красного канала

plt.imshow(red_channel, cmap='gray')
plt.colorbar()
plt.show()


### Многоклассовая классификация
На этом уроке вы разберёте, что такое многоклассовая классификация (англ. multi-class classification) и как она устроена.

В такой классификации объекты принадлежат не одному из двух классов, а одному из нескольких.

Допустим, вы работаете с тремя классами объектов. Так будет выглядеть логистическая регрессия в виде нейронной сети:


<img src = 'https://raw.githubusercontent.com/trisha00001/file/main/x1_1586169772.jpg'>

Получилась полносвязная сеть, в выходном слое которой не один, а три нейрона. Каждый нейрон отвечает за свой класс. Если на выходе z1 будет очень большое положительное значение, то нейронная сеть посчитает, что у объекта класс «1».

Как вычислить функцию потерь? Повторите бинарную кросс-энтропию:

ВСЕ =  - log(p)

Если значение целевого признака — 1, то вероятность правильного ответа равна:


$p=\sigma(x)$

Если значение целевого признака — 0, то p равна:

$p=(1 - \sigma(x)$)

В примере классов три, но вычисление функции потерь не поменяется. Только называться она будет CE (англ. cross-entropy, «кросс-энтропия»):

ВСЕ = - log(p)

где p — вероятность правильного класса, которую вернула нейросеть.

Откуда взять вероятность? Раньше её получали сигмоиды. Что если после каждого нейрона в выходном слое поставить сигмоиду?

In [ ]:
p_1 (вероятность первого класса) = σ(z_1)
p_2 (вероятность второго класса) = σ(z_2)
p_3 (вероятность третьего класса) = σ(z_3)

Все вероятности варьируются от 0 до 1, но сумма этих вероятностей не обязательно будет равна единице. Если предположить, что объект относится только к одному классу, должно получиться такое равенство:

In [ ]:
p_1 + p_2 + p3 = 1

Функция активации, которая здесь подойдёт, называется SoftMax (англ. «мягкий максимум»). Она принимает несколько выходов сети и возвращает вероятности, сумма которых равна единице.

$SoftMax(z_{i})=\frac{exp(z_{i})}{\sum_j^{} z_{j}}$

Вероятности будут вычисляться так:

$p1 = SoftMax(z1) = e^{z_{1}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}})$

$p2 = SoftMax(z2) =  e^{z_{2}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}})$

$p3 = SoftMax(z3) =  e^{z_{3}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}})$


Теперь p₁ варьируется от 0 до 1.

Причём если z₁ значительно больше z₂ и z₃, то в формуле $e^{z_{1}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}})$ числитель примерно равен знаменателю, то есть p₁≈1.

Если z₁ значительно меньше z₂ или z₃, то в формуле $e^{z_{1}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}})$ числитель сильно меньше знаменателя, то есть p₁≈0.

Теперь сумма вероятностей равна единице:

$p1 + p2 + p3 = SoftMax(z1) + SoftMax(z2) + SoftMax(z3) =
= e^{z_{1}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}}) + e^{z_{2}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}}) + e^{z_{3}} / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}}) = = (e^{z_{1}} + e^{z_{2}} + e^{z_{3}}) / (e^{z_{1}} + e^{z_{2}} + e^{z_{3}}) = 1$

Схема нашей нейросети с функцией активации SoftMax выглядит так:

<img src = 'https://raw.githubusercontent.com/trisha00001/file/main/x1_1586169942.jpg'>

Почему SoftMax изображен как блок, зависящий от всех выходов из сети?

Чтобы получить каждую вероятность, действительно нужны все выходы.
Если классов будет больше трёх, нейронов в выходном слое будет столько же, сколько классов, а все их выходы передадутся в SoftMax.

Вероятности из SoftMax на этапе обучения перейдут в кросс-энтропию, которая и посчитает ошибку. Функция потерь будет минимизирована методом градиентного спуска. Ему достаточно, чтобы у функции была производная по всем параметрам: весам и смещению нейронной сети.

Посмотрите, как изменится код. Если в бинарной классификации инициализация последнего слоя выглядела так:

In [ ]:
Dense(units=1, activation='sigmoid'))

В многоклассовой классификации она будет такой:


In [ ]:
Dense(units=3, activation='softmax'))

###Классификация изображений

Попробуйте решить задачу многоклассовой классификации на изображениях.
В вашем распоряжении [такой датасет](https://github.com/zalandoresearch/fashion-mnist). Для агрегатора магазинов одежды нужно сделать классификатор на 10 классов. Каждый класс будет отвечать за определённую категорию товаров и отражён на сайте агрегатора:




<img src ='https://github.com/trisha00001/file/blob/main/Screenshot%202024-03-31%20143223.png?raw=true'>

Вы будете работать с изображениями, потому что описания товаров могут содержать некорректную информацию, их может быть слишком много и причём на разных языках.

На входе модель будет получать чёрно-белую фотографию товара.

Задание

1.
Посмотрите на данные. Мы уже загрузили выборки, разбили их на признаки и целевой признак.

Выведите на экран размеры признаков в обеих выборках. Затем напечатайте значение целевого признака первого изображения из обучающей выборки. Само изображение выведите в чёрно-белом цвете (уже в прекоде).

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

print("Обучающая:", features_train.shape)
print("Тестовая:", features_test.shape)

print("Класс первого изображения:", target_train[0])
plt.imshow(features_train[0], cmap='gray')

2.
В полносвязных сетях подаваемые на вход объекты должны быть строками таблицы, а весь датасет — двумерной таблицей. Чтобы не было ошибки, преобразуйте датасет из трёхмерного массива в двумерную таблицу. Для этого вам понадобится метод np.array.reshape() (от англ. «изменить размер»).

Преобразуйте features_train так, чтобы в первом значении features_train.shape было количество объектов, а во втором — количество пикселей в изображении. Таким же способом измените features_test. Напечатайте на экране новые размеры массивов (уже в прекоде).

In [ ]:

import matplotlib.pyplot as plt
import numpy as np

features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

features_train = features_train.reshape(features_train.shape[0], 28 * 28)
features_test = features_test.reshape(features_test.shape[0], 28 * 28)

print("Обучающая:", features_train.shape)
print("Тестовая:", features_test.shape)

3.
Постройте и обучите нейронную сеть. Начните с простого — создайте модель логистической регрессии с десятью классами в Keras.

Вам понадобится:
- Функция активации 'softmax';
- Функция потерь 'sparse_categorical_crossentropy' (англ. «разрежённая категориальная кросс-энтропия»).

Слово sparse говорит о способе кодирования ответов. В задаче требуется просто номер класса, поэтому выбор пал на эту функцию потерь.

Когда ответы кодируются One-Hot-Encoding и классу 9 соответствует целый вектор [0, 0, 0, 0, 0, 0, 0, 0, 1], применяют categorical_crossentropy().

Обучите сеть на одной эпохе. Напечатайте прогресс обучения и значения точности на обучающей и тестовой выборках.

In [ ]:
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

features_train = features_train.reshape(features_train.shape[0], 28 * 28)
features_test = features_test.reshape(features_test.shape[0], 28 * 28)

model = keras.models.Sequential()
model.add(keras.layers.Dense(10, activation='softmax', input_dim=784))
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])
model.fit(features_train, target_train, epochs=1, verbose=2, validation_data=(features_test, target_test))

###Обучение многослойной сети [GPU]

В этом уроке вы разберётесь, как обучать модели на сервере.
Прежде чем запустить модель на сервере, нужно дождаться своей очереди к нему. Время ожидания зависит от загруженности сервера и может составить 2,5 часа. Это нормально при работе с нейросетями, когда требуются большие вычислительные мощности. Даже в крупных компаниях иногда приходится «подкупать» коллег печеньками, чтобы они уступили очередь.

Чтобы решение задач на GPU не заняло много времени, учтите эти рекомендации:
- Не откладывайте задачи на потом: в конце спринта очередь может быть ещё больше. Всего задач с GPU будет пять.
- Настройте обучение так, чтобы на экран выводилась информация о прогрессе обучения. Это позволит быстрее найти и исправить ошибку.
- Перед отправкой кода на сервер проверьте его на своём компьютере. Не торопитесь: убедитесь, что до обучения модели код действительно работает.
Перед тем как поставить задачу в очередь, мы тоже проверим ваш код.

Для предварительной проверки кода создайте в нём три функции:
1. Загрузка обучающей выборки


In [ ]:
def load_train(path):
    ...

Загрузите в эту функцию обучающую выборку и командой return верните пару с переменными «признаки и целевой признак». Путь к файлам находится в параметре path.

In [ ]:
def load_train(path):
    features_train = np.load(path + 'train_features.npy')
    target_train = np.load(path + 'train_target.npy')
    features_train = features_train.reshape(features_train.shape[0], 28 * 28) / 255.
    return features_train, target_train

Загружать в эту функцию тестовую выборку не нужно: сервер загрузит её сам.

Яркость изображений из обучающей выборки приведите к диапазону [0, 1]. В этом диапазоне всегда находится яркость изображений из тестовой.

2. Создание модели

In [ ]:
def create_model(input_shape):
    ...

Создайте модель для нейронной сети и верните её командой return. Чтобы указать размер данных в первом слое, примените параметр input_shape.

Вот пример с логистической регрессией:


In [ ]:
def create_model(input_shape):
    model = Sequential()
    model.add(Dense(10, input_shape=input_shape, activation='softmax'))
    model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy',
                  metrics=['acc'])

    return model

Убедитесь, что в этой части кода нет долгих операций (например, обучение модели), иначе предварительную проверку код не пройдёт.

Запуск модели

In [ ]:
def train_model(model, train_data, test_data, batch_size, epochs,
                steps_per_epoch, validation_steps):
    ...

Обучите и верните её командой return.

Функция получает на вход:
- модель,
- обучающую и тестовую выборку,
- аргументы для метода fit().

Аргументы нужны, чтобы перед отправкой на сервер код можно было проверить на небольшом числе объектов. Нужные значения для них запишите как значения по умолчанию.

In [ ]:
def train_model(model, train_data, test_data, batch_size=32, epochs=5,
                # эти аргументы разберём позже, поэтому пока не указываем
                steps_per_epoch=None, validation_steps=None):

Рассмотрим пример с логистической регрессией:

In [ ]:
def train_model(model, train_data, test_data, batch_size=32, epochs=5,
                steps_per_epoch=None, validation_steps=None):

    features_train, target_train = train_data
    features_test, target_test = test_data
    model.fit(features_train, target_train,
              validation_data=(features_test, target_test),
              batch_size=batch_size, epochs=epochs,
              steps_per_epoch=steps_per_epoch,
              validation_steps=validation_steps,
              verbose=2, shuffle=True)

    return model

Вашей валидационной выборкой в методе fit() будет тестовая.

Посмотрите на весь код для логистической регрессии:

In [ ]:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np


def load_train(path):
    features_train = np.load(path + 'train_features.npy')
    target_train = np.load(path + 'train_target.npy')
    features_train = features_train.reshape(features_train.shape[0], 28 * 28) / 255.
    return features_train, target_train


def create_model(input_shape):
    model = Sequential()
    model.add(Dense(10, input_shape=input_shape, activation='softmax'))
    model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy',
                  metrics=['acc'])

    return model


def train_model(model, train_data, test_data, batch_size=32, epochs=5,
               steps_per_epoch=None, validation_steps=None):

    features_train, target_train = train_data
    features_test, target_test = test_data
    model.fit(features_train, target_train,
              validation_data=(features_test, target_test),
              batch_size=batch_size, epochs=epochs,
              steps_per_epoch=steps_per_epoch,
              validation_steps=validation_steps,
              verbose=2, shuffle=True)

    return model

Чтобы выполнить задание, перейдите на курс «Компьютерное зрение — практика обучения нейронных сетей», выберите тему «Полносвязные сети», а в теме урок «Обучение многослойной сети [GPU]».